import logo from './spinDie.webp';
import './App.css';
import SetDie from './setDie.js';
import Roll from './Roll.js';
import {useState} from 'react';

function App() {
  const [data, setData] = useState({});
  const updateData = (dieStats) => {
    setData(dieStats);
  };

  return (
    <div className="App">
    {/*I actually really liked the default
    page generated by React when the project 
    was first packed, so I saved some of that
    code, put in my own colors and visuals, and
    turned it into the header of my page, rather
    than deleting it altogether*/}
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Welcome to the Quixotic-Dragons dice roller!
        </p>
      </header>
      <body>
      {/*SetDie uses a form to allow 
      the user to set the number of 
      sides on the die they want to 
      roll, as well as how many of 
      said die to roll- Eventually I 
      plan to allow users to select 
      multiple types of dice to roll 
      at once, such as 1d8 + 2d6*/}
        <SetDie callback={updateData} />
      {/*Roll actually handles the random
      number generation of rolling, using 
      the quantity and die size passed in 
      from SetDie.*/}
      <p>Rolling {"quantity" in data ? data["quantity"]: 0} {"size" in data ? data["size"]: 0}-sided dice.</p>
        <Roll quantity={data["quantity"]} size={data["size"]}/>
      </body>
    </div>
  );
}

export default App;